# Generated by Django 5.2.4 on 2025-09-14 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='counsellor',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='counsellor',
            name='specialization',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
