# Generated by Django 5.2.4 on 2025-09-16 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_counsellor_description_counsellor_specialization'),
    ]

    operations = [
        migrations.AddField(
            model_name='counsellor',
            name='qualification',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='counsellor',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='counsellor',
            name='specialization',
            field=models.CharField(blank=True, choices=[('stress_management', 'Stress Management'), ('career_guidance', 'Career Guidance'), ('mental_health', 'Mental Health Support'), ('marriage_relationship', 'Marriage and Relationship'), ('addiction', 'Addiction Counselling'), ('grief_loss', 'Grief and Loss'), ('self_esteem', 'Self-Esteem and Personal Growth'), ('family_therapy', 'Family Therapy'), ('trauma_ptsd', 'Trauma and PTSD'), ('eating_disorders', 'Eating Disorders Support'), ('child_adolescent', 'Child and Adolescent'), ('anger_management', 'Anger Management'), ('mindfulness', 'Mindfulness and Meditation'), ('financial_stress', 'Financial Stress'), ('lgbtq', 'LGBTQ+ Affirmative Therapy')], max_length=255),
        ),
    ]
